=== SparkleX/z1/packages/sparkle-core/resources/schema/table.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"additionalProperties": {
			"type": "boolean"
		},
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"primaryKey": {
			"type": "array"
		},
		"columns": {
			"$ref": "#/definitions/columns"
		}
	},
	"additionalProperties": false,
	"definitions": {
		"columns": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/column"
			}
		},
		"column": {
			"type": "object",
			"required": ["type"],
			"properties": {
				"type": {
					"type": "string",
					"enum": ["string", "number", "datetime", "decimal", "guid"]
				},
				"format": {
					"type": "string",
					"enum": ["amount", "price", "quantity", "measure"]
				},
				"size": {
					"type": "number"
				},
				"default": {
					"type": "string"
				},
				"values": {
					"$ref": "#/definitions/validValues"
				},
				"editSize": {
					"type": "number"
				}
			},
			"additionalProperties": false
		},
		"validValues": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		}
	}
}

=== SparkleX/z1/packages/z1-domain/domain/OITM.table.json
{
	"name": "OITM",
	"description": "Item Master Data",
	"primaryKey": [
		"ItemCode"
	],
	"columns": {
		"Id": {
			"type":"guid"
		},
		"ItemCode": {
			"type": "string",
			"editSize": 8
		},
		"ItemName": {
			"type": "string",
			"editSize": 10
		},
		"IsSales": {
			"type": "string",
			"default": "N",
			"values": {
				"Y": "desc",
				"N": "No"
			}
		},
		"IsStock": {
			"type": "string",
			"default": "N",
			"values": {
				"Y": "Yes",
				"N": "No"
			}
		},
		"TaxLiable": {
			"type": "string",
			"default": "N",
			"values": {
				"Y": "Yes",
				"N": "No",
				"U": "NA"
			}
		}
	}
}
