=== SparkleX/z1/packages/core-domain-builder/schema/domain.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"additionalProperties" : {
			"type" : "boolean"
		},
		"type" : {
			"type" : "string"
		},
		"title" : {
			"type" : "string"
		},
		"description": {
			"type": "string"
		},
		"primaryKey": {
			"type": "array"
		},
		"properties": {
			"$ref": "#/definitions/properties"
		}
	},
	"additionalProperties": false,
	"definitions": {
		"properties": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/property"
			}
		},
		"property": {
			"type": "object",
			"required": [
				"type"
			],
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"string",
						"number"
					]
				},
				"format" : {
					"type" : "string", 
					"enum" : ["date-time"]
				},
				"maxLength": {
					"type": "number"
				},
				"default": {
					"type": "string"
				},
				"values": {
					"$ref": "#/definitions/validValues"
				},
				"editSize": {
					"type": "number"
				},
				"editType": {
					"type": "string",
					"enum": [
						"amount",
						"price",
						"quantity",
						"measure"
					]
				}
			},
			"additionalProperties": false
		},
		"validValues": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		}
	}
}

=== SparkleX/z1/packages/z1-domain/domain/ORDR.table.json
{
	"title": "ORDR",
	"description": "Sales Order",
	"primaryKey": [
		"DocEntry"
	],
	"additionalProperties": false,
	"properties": {
		"DocEntry": {
			"type": "number"
		},
		"CardCode": {
			"type": "string",
			"maxLength": 64
		},
		"CardName": {
			"type": "string",
			"maxLength": 255
		},
		"DocDate": {
			"type": "string",
			"format": "date-time"
		},
		"DocDueDate": {
			"type": "string",
			"format": "date-time"
		}
	}
}
