=== SparkleX/z1/packages/temp/core-joiner/schema/semantic.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"properties": {
        "$schema": {
            "type": "string"
		},		
        "name": {
			"type": "string",
			"minLength": 1,
  			"maxLength": 20
        },
        "description": {
            "type": "string"
		},
		"foundation": {
			"type": "string"
		},
		"columns":{
			"$ref": "#/definitions/columns"
		}		
	},
	"additionalProperties": false,
    "definitions": {
        "columns":{
			"type": "object",
			"additionalProperties": 
			{ 
				"$ref": "#/definitions/column"
			}
		},
		"column":{
			"type": "object",
			"required": ["type","description"],
			"properties": {
				"type":{
					"type": "string",
					"enum": ["dimension", "measure"]
				},
				"description":"string",
				"aggression": {
					"type": "string",
					"enum": ["sum", "max", "min", "avg"]
				}
			},
			"additionalProperties": false
		}					
    }	
}

=== SparkleX/z1/packages/temp/core-joiner/test/metadata/semantic/Journal.semantic.json
{
	"$schema": "../../../schema/semantic.json",
	"name": "Journal",
	"description": "Journal",
	"foundation": "test/metadata/foundation/Accounting.foundation.json",
	"columns": {
		"Journal.id":{
			"type":"dimension",
			"description": "Journal ID"
		},
		"Journal.balance":{
			"type":"measure",
			"description": "Journal ID",
			"aggression": "sum"
		},		
		"JournalLine.id":{
			"type":"dimension",
			"description": "JournalLine ID"
		},
		"JournalLine.lineNum":{
			"type":"dimension",
			"description": "JournalLine ID"
		},		
		"JournalLine.credit":{
			"type":"measure",
			"description": "Credit Amount",
			"aggression": "sum"
		},		
		"JournalLine.debit":{
			"type":"measure",
			"description": "Debit Amount",
			"aggression": "sum"
		},
		"Account.code":{
			"type":"dimension",
			"description": "Account Code"
		}
	}	
}
