=== SparkleX/z1/packages/core-joiner/schema/foundation.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"name": {
			"type": "string",
			"minLength": 1,
			"maxLength": 20
		},
		"description": {
			"type": "string"
		},
		"tables": {
			"$ref": "#/definitions/tables"
		},
		"joins": {
			"$ref": "#/definitions/joins"
		}
	},
	"additionalProperties": false,
	"definitions": {
		"joins": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/join"
			}
		},
		"join": {
			"type": "object",
			"required": [
				"left",
				"right",
				"on"
			],
			"properties": {
				"left": {
					"type": "string"
				},
				"right": {
					"type": "string"
				},
				"on": {
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"tables": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/table"
			},
			"additionalProperties": false
		},		
		"table": {
			"type": "object",
			"required": [
				"table",
				"description"
			],
			"properties": {
				"alias": "string",
				"table": "string",
				"description":"string"
			},
			"additionalProperties": false
		}
	}
}

=== SparkleX/z1/packages/core-joiner/test/metadata/foundation/Accounting.foundation.json
{
	"$schema": "../../../schema/foundation.json",
	"name": "Account",
	"description": "Account",
	"tables": [
		{
			"alias":"Account",
			"table":"Account",			
			"description":""
		},
		{
			"alias":"Cashflow",
			"table":"Cashflow",
			"description":""
		},
		{
			"alias":"Journal",
			"table":"Journal",
			"description":""
		},
		{
			"alias":"JournalLine",
			"table":"JournalLine",
			"description":""
		},
		{
			"alias":"name",
			"table":"JournalCashflow",
			"description":""
		}	
	],
	"joins" : [
		{
			"left":"Journal",
			"right":"JournalLine",
			"on":"Journal.id = JournalLine.id"
		},
		{
			"left":"JournalLine",
			"right":"Account",
			"on":"JournalLine.account = Account.id"
		}		
	]
}
